### ISSUE TITLE
Can't run pls

### ISSUE THREAD

**Issue by drimerdev** [guedesfelipe/pls-cli#100]
I'm installing pls at the second time and it gives me a error
![Screenshot_20240124-131226.png](https://github.com/guedesfelipe/pls-cli/assets/121459810/c70d255e-86c0-43fb-b233-e7c0685d53b3)

Apparently it can't find the "pkg_resources" module and don't start

**Comment by guedesfelipe** [comment]
What is your OS?

Apparently you didn't install the `python-setuptools` package on your distro
