### ISSUE TITLE
Is this a fork of NayamAmarshe/please ?

### ISSUE THREAD

**Issue by shellwhale** [guedesfelipe/pls-cli#29]
Hi ! I was trying to reinstall your tool but was having a hard time finding it back. Is https://github.com/NayamAmarshe/please the originally project that you forked?

**Comment by guedesfelipe** [comment]
Hi!

**PLS-CLI** is not a fork, but it served as an inspiration. **PLS-CLI** is fully customizable and with some code improvements. (And many more things to come)

Were you able to re-install? If you find any problem to re-install **PLS-CLI** post it here and we'll help you!

**Comment by shellwhale** [comment]
Yes I managed to reinstall, I was just confused by the name. I don't remember where I came across **PLS-CLI**, I recently reinstalled Windows and was searching back for it, **please** was practically the only thing I could find. I had to perform an Google advanced search with the environment variables name you've setup (I had them saved). Maybe you should consider changing the name?

**Comment by guedesfelipe** [comment]
The name will remain the same. By the way, I will improve the SEO for the website.
