### ISSUE TITLE
`pls quotes`

### ISSUE THREAD

**Issue by TechWiz-3** [guedesfelipe/pls-cli#49]
What is the expected output for `pls quotes`? All I'm getting is this:

<img width="808" alt="Screen Shot 2022-11-10 at 2 51 13 pm" src="https://user-images.githubusercontent.com/75515581/200996665-38b95015-74c6-4020-ae99-db75c1adcd34.png">

**Comment by guedesfelipe** [comment]
You can type `pls quotes --help`:

![image](https://user-images.githubusercontent.com/25853920/201229328-42d0ca5d-992d-4a3f-aa8e-a008f0a7ee5b.png)

**Comment by TechWiz-3** [comment]
Ahhh that makes sense, so it tells `pls` whether to print quotes or not 👍


Thanks
